name: Harpocrates Security Pipeline

on: [push, pull_request]

jobs:
  security-audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install bandit safety
        
    - name: Run Unit Tests
      run: python -m unittest discover tests
      
    - name: Security Scan (Bandit)
      run: bandit -r core/ app/ -f custom